apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-rest-api-example
  labels:
    app: api-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-rest
  template:
    metadata:
      labels:
        app: api-rest
    spec:
      containers:
      - name: nodejs-rest-api-example
        image: femartin/nodejs-rest-api-example
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: api-rest-service
spec:
  selector:
    app: api-rest
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 4000
      nodePort: 32330
      targetPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: database-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 6000
