apiVersion: v1
kind: Service
metadata:
  name: api-rest-service
spec:
  selector:
    version: v2
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 4000
      nodePort: 32330
      targetPort: 4000
